### ISSUE TITLE
js and css not available.

### ISSUE THREAD

**Issue by Jdroy15** [yatharth2209/Three-Level-Authentication-System#1]
can you please provide the javascript and css files of this project?!

**Comment by yatharth-singhal** [comment]
This project mainly uses bootstrap.css, font-awesome.css, and jquery for CSS and Javascript. Apart from that, all the other CSS and JS part is coded within the PHP file. You can download bootstrap, jquery, and font-awesome from the internet. Ensure that CSS files are within the "css" folder and jquery is within a folder called "js".
